// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsAUmlzzhX43hifs0x62pvlEOUnB-jt6g',
    appId: '1:329560075303:web:dac34435cb7969925bf202',
    messagingSenderId: '329560075303',
    projectId: 'bikalk-69dba',
    authDomain: 'bikalk-69dba.firebaseapp.com',
    storageBucket: 'bikalk-69dba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmyYLwnkmTE3TYl4I6iUjPLgONh9Rm9sc',
    appId: '1:329560075303:android:4627e7227b4ade525bf202',
    messagingSenderId: '329560075303',
    projectId: 'bikalk-69dba',
    storageBucket: 'bikalk-69dba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs17d47w4bxJMlnhd5CqlcilM0jK9qV9o',
    appId: '1:329560075303:ios:23ab6caeaf04a2765bf202',
    messagingSenderId: '329560075303',
    projectId: 'bikalk-69dba',
    storageBucket: 'bikalk-69dba.firebasestorage.app',
    iosBundleId: 'com.example.bikalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs17d47w4bxJMlnhd5CqlcilM0jK9qV9o',
    appId: '1:329560075303:ios:23ab6caeaf04a2765bf202',
    messagingSenderId: '329560075303',
    projectId: 'bikalk-69dba',
    storageBucket: 'bikalk-69dba.firebasestorage.app',
    iosBundleId: 'com.example.bikalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsAUmlzzhX43hifs0x62pvlEOUnB-jt6g',
    appId: '1:329560075303:web:2ca8b027fa439b935bf202',
    messagingSenderId: '329560075303',
    projectId: 'bikalk-69dba',
    authDomain: 'bikalk-69dba.firebaseapp.com',
    storageBucket: 'bikalk-69dba.firebasestorage.app',
  );
}
